config/routes.rb
Rails.application.routes.draw do
  resources :sync_requests
  resources :profiles
  get 'profile/autoupdate', to: "profiles#autoupdate"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_many :sync_requests, dependent: :destroy

  def in_process?
    SyncRequest.find_by(profile_id: id, status: "in_process") ? true : false
  end
end

app/models/sync_request.rb
class SyncRequest < ApplicationRecord
  belongs_to :profile
  enum status: [:awaiting, :in_process, :done]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update]

  def index
    @profiles = Profile.all
  end

  def show
    @sync_requests = @profile.sync_requests
  end

  def edit
  end
  
  def update
    if @profile.update(profile_params)
      redirect_to @profile, notice: 'The profile has been successfully updated manually.'
    else
      render :edit
    end
  end
  
  def autoupdate
    @profile = Profile.find(params[:format])
    QueryCreatorService.new(@profile).perform
    redirect_to @profile, notice: 'A profile update request has been successfully created.'
  end

  private

  def set_profile
    @profile = Profile.find(params[:id])
  end

  def profile_params
    params.require(:profile).permit(:name, :surname, :city, :company)
  end
end

app/controllers/sync_requests_controller.rb
class SyncRequestsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sync_requests_helper.rb
module SyncRequestsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProfileDatabase</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <h2><%= pluralize(profile.errors.count, "error") %> prohibited this link from being saved:</h2>

    <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <br>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <br>
  <%= form.label :surname %>
  <%= form.text_field :surname %>
  <br>
  <%= form.label :city %>
  <%= form.text_field :city %>
  <br>
  <%= form.label :company %>
  <%= form.text_field :company %>
  <br>
  <%= form.submit %>
<% end %>

app/views/profiles/_profile.html.erb
<%= profile.name %>
<%= profile.surname %>
<%= profile.city %>
<%= profile.company %>
<%= link_to 'show', profile %>
<br>

app/views/profiles/_sync_request.html.erb
Created 
<%= time_ago_in_words(sync_request.created_at) %>
 ago. Status: 
<%= sync_request.status %>
<br>

app/views/profiles/edit.html.erb
<h1>Request page</h1>

<%= render 'form', profile: @profile %>

<br>
<%= link_to 'Show', @profile %> |
<%= link_to 'Index', profiles_path %>

app/views/profiles/index.html.erb
<%= render @profiles %>

app/views/profiles/show.html.erb
Name: <%= @profile.name %><br>
Surname: <%= @profile.surname %><br>
City: <%= @profile.city %><br>
Company: <%= @profile.company %><br><br>
All SyncRequests:<br>
<%= render partial: 'sync_request', collection: @sync_requests %>
<br>
<p id="notice"><%= link_to "#{notice}", @profile %></p>
<%= link_to 'Auto update', profile_autoupdate_path(@profile) %> |
<%= link_to 'Manu Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>